name: image_archive_share
description: "A simple application to create uncompressed archives of images for sharing."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^2.0.9
  archive: ^3.1.6
  share_plus: ^4.0.4
  provider: ^6.0.2
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/launcher_icon.png"

flutter:
  uses-material-design: true